module ITensorMPS
using ITensors
include("imports.jl")
include("exports.jl")
include("abstractmps.jl")
include("mps.jl")
include("mpo.jl")
include("sweeps.jl")
include("abstractprojmpo/abstractprojmpo.jl")
include("abstractprojmpo/projmpo.jl")
include("abstractprojmpo/diskprojmpo.jl")
include("abstractprojmpo/projmposum.jl")
include("abstractprojmpo/projmps.jl")
include("abstractprojmpo/projmpo_mps.jl")
include("abstractprojmpo/core_projmpo.jl")   # factor-core matvec operator (+ CoreProjMPO)
include("abstractprojmpo/fused_mpo_helpers_partial_matvec.jl")   # partial fused H1·H2 matvec (aliased HPHP, dense ψ)
include("abstractprojmpo/fused_mpo_helpers_env.jl")              # fused makeL/makeR env kernel + fused_position!
include("observer.jl")
include("dmrg_debug.jl")             # profiling / trace helpers for the dmrg sweep loop
include("dmrg.jl")
include("dmrg_php.jl")               # aliased-PHP + dense-ψ driver (run_mode :standard/:fused)
include("factor_core_dmrg.jl")      # core-mode DMRG (:core_php), separated from dmrg.jl
include("adapt.jl")
include("opsum_to_mpo/matelem.jl")
include("opsum_to_mpo/qnmatelem.jl")
include("opsum_to_mpo/opsum_to_mpo_generic.jl")
include("opsum_to_mpo/opsum_to_mpo.jl")
include("opsum_to_mpo/opsum_to_mpo_qn.jl")
include("deprecated.jl")
include("defaults.jl")
include("update_observer.jl")
include("lattices/lattices.jl")
include("solvers/ITensorsExtensions.jl")
using .ITensorsExtensions: to_vec
include("solvers/applyexp.jl")
include("solvers/defaults.jl")
include("solvers/update_observer.jl")
include("solvers/timedependentsum.jl")
include("solvers/tdvporder.jl")
include("solvers/sweep_update.jl")
include("solvers/alternating_update.jl")
include("solvers/tdvp.jl")
include("solvers/dmrg.jl")
include("solvers/dmrg_x.jl")
include("solvers/reducedcontractproblem.jl")
include("solvers/contract.jl")
include("solvers/reducedconstantterm.jl")
include("solvers/reducedlinearproblem.jl")
include("solvers/linsolve.jl")
include("solvers/expand.jl")
include("lib/Experimental/src/Experimental.jl")
end
